spring.application.name=vanguard-ratelimiter
# Enable Java 21 Virtual Threads
spring.threads.virtual.enabled=true

# MySQL Configuration
spring.datasource.url=jdbc:postgresql://ep-cold-dream-apoa6n7k-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QPtnpHSjx3c0
spring.jpa.hibernate.ddl-auto=update
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n